[phases.setup]
nixPkgs = ["nodejs_18", "nodePackages.npm"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx http-server dist -p ${PORT:-8080} -a 0.0.0.0 -c-1"