[phases.setup]
# Instala apenas Node 18 (e o npm que já vem junto)
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
# Servir a pasta dist no PORT do Railway
cmd = "npx serve -s dist -l ${PORT:-8080} -n"