// <auto-generated />
using System;
using DoseEmDia.Models.db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DoseEmDia.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251020011806_AdicionarCampoLoteEmVacinas")]
    partial class AdicionarCampoLoteEmVacinas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DoseEmDia.Models.Endereco", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdEndereco");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEndereco"));

                    b.Property<long>("CepId")
                        .HasColumnType("bigint");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdEndereco");

                    b.HasIndex("CepId");

                    b.ToTable("Endereco", (string)null);
                });

            modelBuilder.Entity("DoseEmDia.Models.Localizacao.Cep", b =>
                {
                    b.Property<long>("IdCep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdCep"));

                    b.Property<string>("Bairro")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<long>("CidadeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.HasKey("IdCep");

                    b.HasIndex("CidadeId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Cep", (string)null);
                });

            modelBuilder.Entity("DoseEmDia.Models.Localizacao.Cidade", b =>
                {
                    b.Property<long>("IdCidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdCidade"));

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("IdCidade");

                    b.HasIndex("EstadoId", "Nome")
                        .IsUnique();

                    b.ToTable("Cidade", (string)null);
                });

            modelBuilder.Entity("DoseEmDia.Models.Localizacao.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("PaisId")
                        .HasColumnType("integer");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("IdEstado");

                    b.HasIndex("PaisId", "Nome")
                        .IsUnique();

                    b.ToTable("Estado", (string)null);
                });

            modelBuilder.Entity("DoseEmDia.Models.Notificacao", b =>
                {
                    b.Property<int>("IdNotificacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdNotificacao");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotificacao"));

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("EmailEnviado")
                        .HasColumnType("boolean")
                        .HasColumnName("EmailEnviado");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("IdNotificacao");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificacoes", (string)null);
                });

            modelBuilder.Entity("DoseEmDia.Models.Pais", b =>
                {
                    b.Property<int>("IdPais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPais"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Url")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("IdPais");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Pais", (string)null);
                });

            modelBuilder.Entity("DoseEmDia.Models.Vacina", b =>
                {
                    b.Property<int>("IdVacina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdVacina");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVacina"));

                    b.Property<DateTime>("DataAplicacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IntervaloEntreDoses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumeroDoses")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroLote")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int?>("ValidadeMeses")
                        .HasColumnType("integer");

                    b.HasKey("IdVacina");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Vacina", (string)null);
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdUser");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUser"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ReceberNotificacoes")
                        .HasColumnType("boolean");

                    b.Property<string>("Salt")
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .HasColumnType("text");

                    b.Property<string>("Sexo")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokenExpiracao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TokenRedefinicaoSenha")
                        .HasColumnType("text");

                    b.HasKey("IdUser");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("DoseEmDia.Models.Endereco", b =>
                {
                    b.HasOne("DoseEmDia.Models.Localizacao.Cep", "Cep")
                        .WithMany("Enderecos")
                        .HasForeignKey("CepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cep");
                });

            modelBuilder.Entity("DoseEmDia.Models.Localizacao.Cep", b =>
                {
                    b.HasOne("DoseEmDia.Models.Localizacao.Cidade", "Cidade")
                        .WithMany("Ceps")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("DoseEmDia.Models.Localizacao.Cidade", b =>
                {
                    b.HasOne("DoseEmDia.Models.Localizacao.Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("DoseEmDia.Models.Localizacao.Estado", b =>
                {
                    b.HasOne("DoseEmDia.Models.Pais", "Pais")
                        .WithMany("Estados")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("DoseEmDia.Models.Notificacao", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithMany("Notificacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DoseEmDia.Models.Vacina", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithMany("Vacinas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.HasOne("DoseEmDia.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("DoseEmDia.Models.Localizacao.Cep", b =>
                {
                    b.Navigation("Enderecos");
                });

            modelBuilder.Entity("DoseEmDia.Models.Localizacao.Cidade", b =>
                {
                    b.Navigation("Ceps");
                });

            modelBuilder.Entity("DoseEmDia.Models.Localizacao.Estado", b =>
                {
                    b.Navigation("Cidades");
                });

            modelBuilder.Entity("DoseEmDia.Models.Pais", b =>
                {
                    b.Navigation("Estados");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Navigation("Notificacoes");

                    b.Navigation("Vacinas");
                });
#pragma warning restore 612, 618
        }
    }
}
