# Força detecção de .NET
providers = ["dotnet"]

[phases.setup]
# Se seu .csproj é net6.0, deixe _6; se for net8.0, troque para _8 em ambos
nixPkgs = ["dotnet-sdk_6", "dotnet-runtime_6"]

[phases.build]
cmds = [
  "dotnet restore",
  "dotnet publish -c Release -o out"
]

[start]
# Ajuste o nome do assembly se for diferente
cmd = "dotnet out/DoseEmDia.dll"