[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore"]

[phases.build]
# Publica com o runtime embutido para Linux x64
cmds = ["dotnet publish -c Release -o out -r linux-x64 --self-contained true /p:UseAppHost=true"]

[start]
# IMPORTANTE: inicia o executável, não a DLL
cmd = "./out/DoseEmDia"