[phases.setup]
# SDK para build + ICU no runtime
nixPkgs = ["dotnet-sdk_8", "icu"]

[phases.install]
cmds = ["dotnet restore"]

[phases.build]
# self-contained para Linux x64 (não depende de runtime externo)
cmds = ["dotnet publish -c Release -o out -r linux-x64 --self-contained true /p:UseAppHost=true"]

[start]
cmd = "./out/DoseEmDia"