[phases.setup]
# Instala SDK e runtime do .NET 6
nixPkgs = ["dotnet-sdk_6", "dotnet-runtime_6"]

[phases.build]
cmds = [
  "dotnet restore",
  "dotnet publish -c Release -o out"
]

[start]
cmd = "dotnet out/DoseEmDia.dll"