# dose-em-dia-backend/DoseEmDia/DoseEmDia/nixpacks.toml

[phases.setup]
# Instale só o SDK; ele já traz o runtime
nixPkgs = ["dotnet-sdk_6"]

[phases.build]
cmds = [
  "dotnet restore",
  "dotnet publish -c Release -o out"
]

[start]
cmd = "dotnet out/DoseEmDia.dll"